version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - CI=true npm run test
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://${DEPLOY_BUCKET}/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://${DEPLOY_BUCKET}/
artifacts:
  files:
    - '**/*'
  base-directory: build
