version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:
    commands:
      - npm install --unsafe-perm
  build:
    commands:
      npm run build --unsafe-perm
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./s3/build s3://${DEPLOY_BUCKET}/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./s3/build/index.html s3://${DEPLOY_BUCKET}/
      - aws s3 cp --recursive ./lambda/build s3://${LAMBDA_BUCKET}/
artifacts:
  files:
    - '**/*'
  base-directory: build
