AWSTemplateFormatVersion: "2010-09-09"
Description: Defines resources to create a lambda function based on a S3 location.
Parameters:
  S3Bucket:
    Type: String
    Description: "Bucket that has the code deploy to lambda"
  S3Key:
    Type: String
    Description: "S3 key of the code to deploy to lambda"
  LambdaRole:
    Type: String
    Description: "ARN of the role the lambda function should assume"
  ProjectName:
    Type: String
    Description: "Prefix for generated AWS resources"
    AllowedPattern: "[a-z0-9][a-z0-9-]{1,50}"
Resources:
  ForwardMessageFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: S3Bucket
        S3Key:
          Ref: S3Key
      Handler: forwardMessage.lambdaHandler
      PackageType: Zip
      Role:
        Ref: LambdaRole
      Runtime: nodejs12.x